services:
  plc-directory:
    image: ghcr.io/zicklag/did-plc-server:plc-053ddecb6a12ce0e996d300f9395899adf02dd05
    platform: linux/amd64 # no arm64 build available
    command:
      - node
      - ../dist/bin.js
    ports:
      - 3001:3000
    environment:
      NODE_ENV: dev
      DATABASE_URL: "postgres://postgres:password@plc-db"
      DEBUG_MODE: 1
      LOG_ENABLED: "true"
      LOG_LEVEL: debug
      LOG_DESTINATION: 1

  plc-db:
    image: postgres
    platform: linux/amd64 # no arm64 build available for plc-directory
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - plc-db-data:/var/lib/postgresql


volumes:
  plc-db-data:
